bibliography: references.bib
link-citations: yes
biblio-style: apalike

# The Context Behind The Categories in Police Misconduct Complaints {#identifying-policing-patterns-from-text}

#### Abstract {-}

In the past few years, police brutality has become part of the national conversation in the United States. The cases that make the news represent only a few of tens of thousands of misconduct complaints brought to police departments every year. Misconduct complaints made to police departments are a rich source of data for understanding patterns in police misconduct. Given that there are widespread variations in how those complaints are classified, even within a given police department, natural language processing can be used to glean insights from the raw text of misconduct complaints. I propose a project that will use Chicago Police Department citizen complaint data to find complaint clusters using natural language processing methods. This work should be useful for journalists and activists who have a vested interest in drawing attention to policing patterns in the interest of creating better police-community relations.

#### Keywords {-}

police abuse, police shootings, police brutality, text analysis, clustering, natural language processing

## Looking Beyond High Profile Misconduct Cases

In the past few years, police brutality has become part of the national conversation in the United States. There have been many high profile incidents in which police officers killed unarmed, usually African-American citizens. These widely-reported cases represent only a few of tens of thousands of misconduct complaints brought to police departments every year. Between March 2011 and September 2015, 28,567 misconduct complaints were brought before the Chicago Police Department (CPD), according to the [Citizens Police Data Project](https://cpdb.co/findings/) [@invisible_institute_citizens_nodate]. Journalists, activists, and other concerned community members want to find patterns in this data in order to work towards a safer, more just relationship between police departments and the citizens they serve. I will work as a data scientist alongside these community stakeholders by using natural language processing to help detect patterns in complaint text.

## Creating Related Clusters Based on Complaint Text

A significant challenge to finding these patterns is the way in which police misconduct complaints are categorized. After a citizen files a complaint to the Civilian Office of Police Accountability, the complaint gets routed either to COPA itself or to the CPD's Bureau of Internal Affairs [@copa_investigative_nodate]. In either institution, whichever individual intakes a complaint has the discretion to choose what single category a complaint is filed under, even though the narrative accounts of many complaints suggest that multiple complaint categories could apply to a single encounter. As a result, the official complaint categories have the potential to obfuscate patterns in the data by reducing multi-faceted reports to single-category labels.

As a data scientist working on this issue alongside journalists, activists, and other community members, I want to return to the raw text in the complaints in order to identify more nuanced complaint categories. We could do this using a number of text analysis methods. I propose the following steps:

* Parse text complaints into individual words or phrases. Care should be taken to correct misspellings and group words by their roots; given that the text complaints will have been written by different authors in varying styles, the tokenization methods should use stemming and lemmatization to identify related words (ex: "grab," "grabbed," and "grabbing" would all map to the same token ID). The tokenization method should also eliminate very common words.   
* Then, use a method like bag-of-words or n-grams to find a representation for each complaint that accounts for the frequency of tokens in the text.
* Next, use a clustering algorithm to generate new categories for the complaints based on the text. We should experiment with different clustering algorithms and different numbers of clusters, then examine the reports in each cluster to determine if they represent cohesive and specific categories.
* Tag each complaint with other relevant features:
     + the time: year, month, date, day of the week, time of day
     + location: neighborhood, cross streets, public vs private space
     + officer data: name, rank, number of misconduct cases against him/her

These additional data tags can be used alongside the text clustering categories in order to find new patterns. For instance, is a certain group of officers always involved in a particular cluster of complaints? Or is there a particular type of complaint that always occurs in a certain neighborhood at the same time of day? For journalists, these patterns can help them tell richer stories about police misconduct. For activists, these patterns can help them identify specific problem areas around which to create awareness campaigns and policy goals. 

## Choosing how to share data

As a data scientist working on this issue, I aim to help my collaborators be deliberate about how they present findings, given the politically charged nature of the national conversation about police misconduct and the complicated politics around police unions and the city government in Chicago. I intend to ensure that my collaborators understand the language processing methods well enough to make responsible use of the findings. My journalist and activist collaborators should consider whether to publish interactive visualizations of the clusters in order to let the public explore the data on their own, or whether to share select findings from the data through their writing and organizing.  If we share the data itself more broadly, we should take cues from groups like the Citizens Police Data Project on how to make the data as accessible as possible, which includes educating the public on how to use and understand the data.