# Trace Your Waste {#gamify-trash}

#### Keywords {-}

environment, climate change, app,

## I want to waste less - kind of

(Start with some statistic about how much trash the average American generates.) Many Americans are aware of this fact and want to generate less waste, but translating that sentiment into action can be hard. It's easy to want to be more environmentally conscious after reading a compelling article about pollution or watching a dramatic documentary about climate change; it's harder to actually make eco-friendly choices while grocery shopping, preparing a family meal, or planning your commute.  

## Enter the TrashDash app

TrashDash is a habit-building app that makes reducing the waste you generate more simple and fun than ever before. The TrashDash app will keep track of all of the trash you generate and motivate you to create less waste over time by tracking your progress towards goals, providing personalized tips based on your recorded waste, and allowing you to compete against your friends.

The TrashDash data science team will create a data pipeline that uses a variety of data collection and machine learning techniques to provide users with a seamless TrashDash experience. Upon first signing up for the app, new TrashDashers will receive a set of compact sensors to put in their primary trash can. ** research the technology here - can the sensors measure weight and take pictures?
- uses CNNS to identify what individual trash items are, corroborates with volume data to give you an overall profile of your waste generation   
- you can take pics of your other trash cans if you want to get really into it
- app will generate a report of your trash generation, show how you stack up against friends/average users, make suggestions about how you can do better

```{r experimental,echo=F,results='asis',eval=F}
data.table::fread('https://raw.githubusercontent.com/UCB-MIDS/experiments-causality/master/data/GerberGreenBook_Chapter3_Donations.csv?token=ABNmuX-Q14rzQ4teItDenc9L5Wo2flncks5ZL5qEwA%3D%3D') %>% stargazer::stargazer(type = 'html',title = 'Something from W241 Experiments and Causality')
```


Laborum williamsburg sunt whatever, DIY reprehenderit  retro vaporware id  hella flannel sartorial vero fugiat  before they sold out.  Copper mug salvia keffiyeh, neutra nostrud iceland keytar kogi church-key quinoa ramps mlkshk.  Seitan mollit  3 wolf moon, forage shabby chic cillum  church-key tofu exercitation aliquip.  Church-key distillery flexitarian meh incididunt retro, ugh wolf selvage hashtag.  Bicycle rights 90's officia  vape.  Listicle post-ironic vape ex.  Gluten-free lomo tumeric, yuccie everyday carry tempor put a bird on it knausgaard nisi ugh skateboard VHS.

## One man's trash is another man's corporate strategy

Millions of TrashDash users, in aggregate, can make a substantial impact on the amount of trash that the United States produces, but just imagine how much larger that impact might be if major companies got involved. TrashDash could amplify its impact - and provide a useful service to companies of all sizes - by building in ways for corporations to take part in TrashDash.
- do it as a corporate caring benefit where companies can "match" employee waste savings by saving waste of their own, or making corresponding donations to conservation orgs
- let companies compete against each other, and the companies that do the best get free advertising to the app's users
